### ISSUE TITLE
Fail to compile on crystal 0.25

### ISSUE THREAD

**Issue by waghanza** [tbrand/neph#62]
Hi,

`neph` fails to compile on last crystal.

**crystal** `0.25.0` has been released **4** days ago and removed `YAML::Type`.

Regards,

**Comment by tbrand** [comment]
Good catch! I believe https://github.com/tbrand/neph/issues/50 contains the fixes as well.

**Comment by waghanza** [comment]
:+1: but if a release could be made with **this** it could help me work on https://github.com/tbrand/which_is_the_fastest :stuck_out_tongue_winking_eye: 

@tbrand At least, I can **downgrade** `crystal`

**Comment by tbrand** [comment]
Oh I see...
Could you delay the release for days?:pray:
I think @notramo will release soon.

How does it sounds @notramo?

**Comment by waghanza** [comment]
@tbrand not a problem for me :stuck_out_tongue: as I can **downgrade** on my `distribution`, however the more important will be when **CI** will update the `crystal` image

**Comment by tbrand** [comment]
Thanks!

**Comment by notramo** [comment]
@waghanza @tbrand 
I've waited for `crystal 0.25` to be available in the Arch Linux repos.
Maybe it could be released earlier before the CI output mode is implemented.
Unfortunately, the new branch also uses `YAML::Type`.
Crystal 0.25 has also `YAML::Type`.
The change is that e.g. `YAML::Any#to_a` returns an `Array(YAML::Any)` instead of `Array(YAML::Type)`.
If somebody want to help porting to Crystal 0.25, the changes needed are mostly replacing `YAML::Type` with `YAML::Any` in some places, and invoking `#to_s`, `#to_a`, `#to_h` etc. when accessing `Array` or `Hash` items.

**Comment by notramo** [comment]
@waghanza @tbrand Please don't close issues until they are solved. Downgrading Crystal is only a temporary workaround.

**Comment by notramo** [comment]
@tbrand @waghanza
 I updated the source code to Crystal 0.25. It was easier than I thought, and the new API of the YAML deserializer is much better.
You can try it. Just check out the `config_redesign` branch. Also, see #63
