### ISSUE TITLE
CI configuration

### ISSUE THREAD

**Issue by waghanza** [tbrand/neph#67]
Hi,

I can see that `travis` is using `osx` to run test phase

The default workers is `linux`, **ubuntu** **LTS**

Why `osx` was selected ?

Regards,

**Comment by notramo** [comment]
@tbrand can configure the CI.
By the way, why is CI used? It is **_very_ slow**. Even my 1.8GHz dual core machine (from 2006) is faster. It is a good thing for projects that has wide platform support, and lot of contributors. But Crystal only supports 4-5 architectures currently (only Linux and macOS on different CPUs), and Neph don't has any platform-specific C binding. And only @waghanza and I are the contributors currently, so every change can be tested manually (in less time). Also, it is very annoying when a build fails only because timeout on slow CPUs in CI machines, although the code is fully correct. Could testing be removed and only used for releasing macOS builds?

**Comment by waghanza** [comment]
@notramo I think CI is a value added to this project, since it use to communicate on stability of this project.
For example, a _green_ **badge** on `README`, is helpful to grow.
As I understand, the main issue you notice is speed / crystal support.

Some CI tools are **faster** that `travis` :
+ https://semaphoreci.com/
+ https://circleci.com/
+ ...

but on all `crystal` support is not **official**

To ensure speed we can change CI tool, but I think `travis` is more than enough (since very simple)

My initial question was : why default was changed (perhaps there is a `great` justification :stuck_out_tongue: )

PS : If `CI` for **releasing** is suggest https://cirrus-ci.org, it the only `CI` I know using
+ Windows
+ Linux
+ OSX

**Comment by waghanza** [comment]
Related to #68
