### ISSUE TITLE
No console output

### ISSUE THREAD

**Issue by waghanza** [tbrand/neph#76]
Hi @tbrand,

When running  `neph`, since some release, I do not have any ouput / progress bar.

Regards,

**Comment by notramo** [comment]
@waghanza The rewritten version didn't have any output, because I planned to implement the job/process managing features, then implement the terminal interface. Since @tbrand reverted my changes without even knowing what he is doing, I don't want to further contribute to this project unless my changes are restored.
If you want progress output, you can use the latest release where @tbrand restored the old behavior.
